version: '3.1'

services:
  steamscout:
    image: evilgenius13/steamscout:v1.0
    container_name: steamscout
    environment:
      - DISCORD_TOKEN=your_discord_token_here
    volumes:
      - steam_scout_data:/app/data

volumes:
  steam_scout_data:
